import Head from "next/head";

import { ProjectsDisplay } from "../components/ProjectsDisplay";

import { Otherpages } from "../components/Otherpages";
import { Contact } from "@/components/Contact";
import { Greeting } from "@/components/Greeting";
import { About } from "@/components/About";
import { Inter } from "next/font/google";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

import { useState, useEffect } from "react";
import { projects } from "../components/data";

const inter = Inter({ subsets: ["latin"] });

export default function Home(darkMode) {
  const [toastTheme, setToastTheme] = useState("dark");
  useEffect(() => {
    darkMode ? setToastTheme("dark") : setToastTheme("light");
  }, [darkMode]);

  return (
    <>
      <Head>
        <title>Portfolio JuandreTech</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/programming.png" />
      </Head>

      <div>
        <div className="min-h-screen  dark:bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] dark:from-gray-800 dark:via-gray-900 dark:to-black">
          <div id="stars" className="z-0"></div>
          <div id="stars2" className="z-0"></div>

          <Greeting />
          <About darkMode={toastTheme} />
          <ProjectsDisplay projects={projects} />
          <Contact darkMode={toastTheme} />
          <Otherpages />
        </div>
        <ToastContainer
          toastStyle={{
            backgroundColor: darkMode ? "black" : "white",
            color: !darkMode ? "black" : "white",
          }}
        />
      </div>
    </>
  );
}
